shortener/urls.py
from django.conf.urls import url

from . import views

app_name = 'shortener'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<url_key>[A-Za-z0-9]+)/$', views.redirect_to_link, name='redirect_to_url'),
    url(r'^!(?P<url_key>[A-Za-z0-9]+)/$', views.detail, name='detail'),
]

shortener_demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('shortener.urls')),
    url(r'^admin/', admin.site.urls),
]

shortener/models.py
from django.conf import settings
from django.db import models

import shortener.utils


def generate_key():
    i = 0
    while i < getattr(settings, 'SHORTENER_URL_KEY_MAX_GENERATION_ATTEMPTS', 16):
        key = shortener.utils.random_key(i)
        try:
            Link.objects.get(url_key=key)
        except Link.DoesNotExist:
            return key
        i += 1
    return shortener.utils.random_key(i)  # may cause IntegrityError


class Link(models.Model):
    url_key = models.CharField(max_length=64, unique=True, default=generate_key)
    redirection_url = models.CharField(max_length=512, unique=True)
    counter = models.IntegerField(default=0)
    submitter = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.redirection_url

shortener/views.py
import random

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from url_normalize import url_normalize

from shortener.models import Link


def index(request):
    try:
        redirection_url = request.POST['redirection_url']
    except KeyError:
        return render(request, 'shortener/index.html')

    normalized_url = url_normalize(redirection_url)
    try:
        validator = URLValidator(schemes=['http', 'https'])
        validator(normalized_url)
    except ValidationError:
        return render(request, 'shortener/index.html', {'error_message': 'Submitted URL is invalid.'})

    user_count = get_user_model().objects.count()
    random_user = get_user_model().objects.all()[random.randrange(user_count)]
    link, create = Link.objects.get_or_create(redirection_url=normalized_url, defaults={'submitter': random_user})
    return HttpResponseRedirect(reverse('shortener:detail', args=(link.url_key,)))


def detail(request, url_key):
    link = get_object_or_404(Link, url_key=url_key)
    return render(request, 'shortener/detail.html', {'link': link})


def redirect_to_link(request, url_key):
    link = get_object_or_404(Link, url_key=url_key)
    link.counter = F('counter') + 1  # avoids race condition
    link.save()
    return HttpResponseRedirect(link.redirection_url)

shortener/templates/shortener/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link href='http://fonts.googleapis.com/css?family=Lato:300,400,900' rel='stylesheet' type='text/css'>

    <style type="text/css">
        body {
            background-color: #3498db;
            font-family: 'Lato', sans-serif;
            font-weight: 300;
            font-size: 16px;
            color: #ffffff;
        }

        h1 {
            margin-top: 60px;
            margin-bottom: 15px;
            color: #ffffff;
            font-size: 45px;
            font-weight: 300;
            letter-spacing: 1px;
        }

        .shortener-form div{
            margin-top: 10px;
        }

        .form-control.link-input {
            height: 46px;
            padding: 6px 11px;
            font-size: 18px;
            width: 100%;
        }

        .content-container{
            margin-top: 30px;
        }

        a{
            color: #ffffff;
        }

        .stat span{
            margin-right: 10px;
        }

    </style>
</head>
<body>
    <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/"><b>LINK SHORTENER</b></a>
        </div>
      </div>
    </div>

    <div class="container">
        <h1>Shorten your link.</h1>

        <form class="shortener-form form-inline row" action="{% url 'shortener:index' %}" method="post">
            {% csrf_token %}
            <div class="col-md-8">
                <input
                        class="form-control link-input col-md-8"
                        type="text"
                        name="redirection_url"
                        placeholder="https://example.com"
                        value="{% block input_value %}{% endblock %}"
                        autofocus="autofocus"
                        onFocus="this.select()"
                        oninput="document.getElementById('submit-button').disabled=false"
                />
            </div>
            <div class="col-md-4">
                <input
                        class="btn btn-default btn-lg"
                        id="submit-button"
                        type="submit"
                        value="Add link"
                        disabled
                />
            </div>
        </form>

        <p class="content-container">
            {% block content %}

            {% endblock %}
        </p>
    </div>
</body>
</html>

shortener/templates/shortener/detail.html
{% extends "shortener/base.html" %}

{% block title %}Shortened link details{% endblock %}


{%  block input_value %}
{{ request.META.HTTP_HOST }}{% url 'shortener:redirect_to_url' link.url_key %}
{% endblock %}


{% block content %}

    <p class="stat"><span class="glyphicon glyphicon-link"></span><a href="{{ link.redirection_url }}">{{ link.redirection_url }}</a></p>
    <p class="stat"><span class="glyphicon glyphicon-download-alt"></span><span>{{ link.counter }}</span></p>
    <p class="stat"><span class="glyphicon glyphicon-user"></span><span>{{ link.submitter.username }}</span></p>

{% endblock %}

shortener/templates/shortener/index.html
{% extends "shortener/base.html" %}


{% block title %}Link shortener{% endblock %}<

{% block content %}
    {% if error_message %}
        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          {{ error_message }}
        </div>
    {% endif %}
{% endblock %}